---
- hosts: all
  become: true
  vars:
    default_container_name: reddit
    default_container_image: kovtalex/otus-reddit:1.0
  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        detach: yes
        published_ports: 9292:9292
        restart_policy: unless-stopped
        state: started
